name: fanticoapp
description: Fantico

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  flutter_svg: ^0.19.1
  after_layout: ^1.0.7+2
  dartz: ^0.9.2
  meta: ^1.2.4
  freezed_annotation: ^0.12.0
  rxdart: ^0.24.1
  adaptive_dialog: ^0.9.3
  get: ^3.25.3
  get_storage: ^1.4.0
  json_annotation: ^3.1.1
  uuid: ^2.2.2
  font_awesome_flutter: ^8.11.0
  flutter_hooks: ^0.15.0
  get_version: ^0.2.2
  flutter_cupertino_date_picker_fork: ^1.0.1
  photo_view: ^0.10.3
  image_picker: ^0.6.7+15
  image_cropper: ^1.3.1
  cached_network_image: ^2.4.1
  flutter_typeahead: ^1.9.1
  dio: ^3.0.10
  youtube_player_flutter: ^7.0.0+7
  wheel_chooser: ^0.1.1
  flare_flutter: ^2.0.6
  google_sign_in: ^4.5.9
  flutter_facebook_auth: ^2.0.0

  bmprogresshud:
    path: packages/bmprogresshud-master

dev_dependencies:
  build_runner: 1.10.11
  freezed: ^0.12.6
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/pages/login/logo.png
    - assets/pages/login/icons/email.svg
    - assets/pages/login/icons/key.svg
    - assets/pages/login/icons/facebook.svg
    - assets/pages/login/icons/apple.svg
    - assets/pages/login/icons/google.svg
    - assets/pages/login/icons/avatar.svg
    - assets/pages/login/icons/twitch.svg
    - assets/pages/login/icons/discord.svg
    - assets/images/
    - assets/svg/
    - assets/animations/notifications.flr
